alias ls="lsd"
alias la="lsd -a"
alias ll="lsd -lha"
alias n="wmname dwm&&neofetch&&wmname LG3D"
alias ra="ranger"
alias man="man -M /usr/share/man/zh_CN"
alias e="exit"
alias l="lsd"
alias cfw="sudo systemctl restart clash-core-service &&/home/jccc/clash_for_windows/cfw"
alias cnpm="npm --registry=https://registry.npmmirror.com --cache=$HOME/.npm/.cache/cnpm --disturl=https://npmmirror.com/mirrors/node --userconfig=$HOME/.cnpmrc"
alias hexos="hexo cl && hexo g && hexo s"
alias cat="bat"
