# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# The following lines were added by compinstall
zstyle :compinstall filename '/home/jccc/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.config/zsh/.zsh_history
HISTSIZE=1000
SAVEHIST=1000
setopt autocd beep extendedglob nomatch notify
# End of lines configured by zsh-newuser-install

# Autocompletion with an arrow-key driven interface
zstyle ':completion:*' menu select


source ~/.config/zsh/alias.zsh
source ~/.config/zsh/vi.zsh
source ~/.config/zsh/ranger.zsh
source /home/jccc/.config/zsh/powerlevel10k/powerlevel10k.zsh-theme
source /home/jccc/.config/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh
source /home/jccc/.config/zsh/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh






# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

