source ~/.config/zsh/.zsh/powerlevel10k/powerlevel10k.zsh-theme
source ~/.config/zsh/.zsh/zsh-autosuggestions-master/zsh-autosuggestions.plugin.zsh
source ~/.config/zsh/.zsh/zsh-syntax-highlighting-master/zsh-syntax-highlighting.plugin.zsh
source ~/.config/zsh/.zsh/zsh-completions-master/zsh-completions.plugin.zsh
source ~/.config/zsh/.zsh/alias.zsh
source ~/.config/zsh/.zsh/ranger.zsh
source ~/.config/zsh/.zsh/vi.zsh
source ~/.config/zsh/.zsh/fzf.zsh


# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.config/zsh/.zsh/.p10k.zsh ]] || source ~/.config/zsh/.zsh/.p10k.zsh
export EDITOR=nvim

#命令补全
autoload -Uz compinit promptinit
compinit
promptinit
set nonomatch # 允许通配符

# 启用彩色提示符
autoload -U colors && colors

# 每次刷新提示符
setopt prompt_subst

# 刷新自动补全
zstyle ':completion:*' rehash true

# 方向键选择补全
zstyle ':completion:*' menu select

# History Search
autoload -Uz up-line-or-beginning-search down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search

[[ -n "${key[Up]}"   ]] && bindkey -- "${key[Up]}"   up-line-or-beginning-search
[[ -n "${key[Down]}" ]] && bindkey -- "${key[Down]}" down-line-or-beginning-search
# 消除历史记录的重复条目
setopt HIST_IGNORE_DUPS

# FZF
# ctrl+R利用fzf查找历史目录
source /usr/share/fzf/key-bindings.zsh
source /usr/share/fzf/completion.zsh


# This will set the default prompt to the walters theme
prompt walters


#解决程序输出问题
unsetopt prompt_cr prompt_sp



cat /home/jccc/.dwm/weather|lolcat
#bitfetch
#export https_proxy=http://127.0.0.1:7890
#export http_proxy=http://127.0.0.1:7890
#export all_proxy=socks5://127.0.0.1:7890
# export https_proxy=""
# export http_proxy=""
# export all_proxy=""
PATH="$PATH:/home/jccc/.local/bin"

source ~/.config/zsh/.zsh/autostartx.zsh
